---
version: "2"

services:
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8888:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  popug-auth:
    build: auth
    ports:
      - "8080:5000"
    depends_on:
      - broker
    environment:
      KAFKA_SERVER: 'broker:9092'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.popug-auth.rule=Host(`id.popug.localhost`)"

  popug-tasks:
    build: task-manager
    ports:
      - "8000:5000"
    depends_on:
      - popug-auth
      - broker
    environment:
      KAFKA_SERVER: 'broker:9092'
      OAUTH_BASE_URL: 'http://id.popug.localhost/'
      BASE_URL: 'http://tasks.popug.localhost/'
      OAUTH_TOKEN_URL: 'popug-auth:8080/o/token/'
      OAUTH_USERINFO_URL: 'popug-auth:8080/account/info'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.popug-tasks.rule=Host(`tasks.popug.localhost`)"
    links:
      - popug-auth


  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

